drivingschool/DSchool/urls.py
from django.urls import path
from . import views

app_name = "DSchool"

urlpatterns = [
    path('students/', views.student, name='student-list'), 
    path("students/<int:pk>/acount", views.student_detail_view, name="student-detail"),
    path('students/<int:pk>/planning', views.planning_view, name='planning-list'),
    path('planning', views.planning, name='planning-list-all'),

    path('students/add-member', views.student_form, name='student_form'),
    path('students/<int:pk>/delete', views.delete_student, name='delete-student'),
    path('students/<int:pk>/to-delete', views.student_to_delete, name='student-to-delete'),
    path('students/<int:pk>/edit', views.edit_student, name='student-to-edit'),

    path('students/<int:pk>/add-rdv', views.add_rdv, name='add-rdv'),



    


]

drivingschool/drivingschool/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path('DSchool/', include('DSchool.urls')),  
]

drivingschool/polls/urls.py
from django.urls import path
from . import views
from django.contrib import admin
admin.site.site_header = 'Driving School Administration'
admin.site.site_title = 'Driving School Administration'


app_name = "polls"
""" with generic view :  """
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

""" with natural view
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
] """

drivingschool/DSchool/models.py
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone


class Student(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    h_total = models.IntegerField(default=0)
    h_remaining = models.IntegerField(default=0)
    def __str__(self):
        return self.username
class Instructor(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    def __str__(self):
        return self.username
    
class Planning(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    date = models.DateTimeField()
    place = models.CharField(max_length=200)
    hour = models.CharField(max_length=200)
    def __str__(self):
        return self.student.username + " " + self.instructor.username + " " + str(self.date) + " " + self.place + " " + self.hour


# Create your models here.

drivingschool/DSchool/forms.py
from django import forms
from .models import Student, Planning

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['username', 'password', 'h_total'] 


class AddPlanningForm(forms.ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Date'  # Étiquette du champ
    )

    class Meta:
        model = Planning
        fields = ['instructor', 'date', 'place']

drivingschool/DSchool/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import DetailView
from django.shortcuts import render
from django.template import loader
from .forms import StudentForm, AddPlanningForm
from django.shortcuts import render, redirect  
from django.views.generic import ListView


from .models import Student, Planning
# Create your views here.


def student(request):
    student_list= Student.objects.all().order_by('-id')
    template = loader.get_template("DSchool/student.html")
    context = {
        "student_list": student_list,
    }
    return HttpResponse(template.render(context, request))


def planning(request):
    planning_list= Planning.objects.all()
    template = loader.get_template("DSchool/planning-all.html")
    context = {
        "planning_liste": planning_list,
    }
    return HttpResponse(template.render(context, request))


def student_detail_view(request, pk):
    student = get_object_or_404(Student, pk=pk)
    context = {
        'student': student,
    }
    return render(request, 'DSchool/student_detail.html', context)    


def planning_view(request, pk):
    student = get_object_or_404(Student, pk=pk)  
    plannings = Planning.objects.filter(student=student)
    context = {
        'student': student,
        'plannings': plannings,
    }
    return render(request, 'DSchool/planning.html', context)



def student_form(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save() 
            return redirect('DSchool:student-list')  
    else:
        form = StudentForm()
    return render(request, 'DSchool/add-student.html', {'form': form})




def student_to_delete(request, pk):
    student = get_object_or_404(Student, pk=pk)
    return render(request, 'DSchool/confirm-delete-student.html', {'student': student})

def delete_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    student.delete() 
    return redirect('DSchool:student-list')
  




def edit_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    form = StudentForm(request.POST or None, instance=student)
    studentTotalDB = student.h_total
    if request.method == 'POST' and form.is_valid():

        new_h_total = int(form.cleaned_data['h_total'])
        if studentTotalDB != new_h_total and new_h_total > studentTotalDB:
           difference = new_h_total - studentTotalDB


           student.h_total = new_h_total
           student.h_remaining += difference

           student.save()

           form.save()

           return redirect('DSchool:student-list')
                   
     


    return render(request, 'DSchool/edit-student.html', {'form': form, 'student': student})





def add_rdv(request, pk):
    student = get_object_or_404(Student, pk=pk)
    
    if request.method == 'POST':
        form = AddPlanningForm(request.POST)
        if form.is_valid():
            planning = form.save(commit=False)
            planning.student = student  
            planning.save()
            return redirect('DSchool:planning-list', pk=student.id)
    else:
        form = AddPlanningForm()

    return render(request, 'DSchool/add-rdv.html', {'form': form, 'student': student})

drivingschool/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

""" Generic Views """

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

""" natural views
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

def vote():same as generic view """

drivingschool/DSchool/templates/DSchool/add-rdv.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add RDV</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .custom-form {
            border: 1px solid #ccc;
            padding: 20px;
            margin-top: 50px;
            text-align: left;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="row justify-content-center">

            <div class="col-6">
                
                <div class="custom-form mx-auto">
                    <h2>Ajouter un rdv pour {{ student.username }}</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group ">
                            {{ form.instructor.label_tag }}
                            {{ form.instructor }}
                        </div>
                        <div class="form-group ">
                            {{ form.date.label_tag }}
                            {{ form.date }}
                        </div>
                        <div class="form-group ">
                            {{ form.place.label_tag }}
                            {{ form.place }}
                        </div>
                    
                        <button type="submit" class="btn btn-dark">Enregistrer</button>
                        <a class="btn btn-dark" href="{% url 'DSchool:student-list'%}">Retour</a>

                    </form>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

drivingschool/DSchool/templates/DSchool/add-student.html
<!DOCTYPE html>
<html>
<head>
    <title>Student Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .custom-form {
            border: 1px solid #ccc;
            padding: 20px;
            margin-top: 50px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">

            <div class="custom-form mx-auto">
                <h2 class="text-center mb-4">Student Form</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group ">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="form-group ">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                    <div class="form-group ">
                        {{ form.h_total.label_tag }}
                        {{ form.h_total }}
                    </div>
                    <div class="form-group ">
                        {{ form.h_remaining.label_tag }}
                        {{ form.h_remaining }}
                    </div>
                    <button type="submit" class="btn btn-dark">Enregistrer</button>
                    <a class="btn btn-dark" href="{% url 'DSchool:student-list'%}">Retour</a>

                </form>
            </div>
        </div>
    </div>

</body>
</html>

drivingschool/DSchool/templates/DSchool/confirm-delete-student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votre Titre</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
    <body>
        <div class="container-fluid mt-5">
            <div class="row justify-content-center">
                <div class="col-4">

                    <h1> Êtes-vous sûr de vouloir supprimer l'étudiant {{ student.username }} ?</h1>
                    <a class="btn btn-danger" href="{% url 'DSchool:delete-student' student.id %}">Confirmer la suppression</a>
                    <a class="btn btn-secondary" href="{% url 'DSchool:student-list' %}">Annuler</a>
                </div>
            </div>
        </div>
    </body> 
</html>

drivingschool/DSchool/templates/DSchool/edit-student.html
<!DOCTYPE html>
<html>
<head>
    <title>Student Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .custom-form {
            border: 1px solid #ccc;
            padding: 20px;
            margin-top: 50px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">

            <div class="custom-form mx-auto">
                <h2 class="text-center mb-4">Student Form</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group ">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>
                    <div class="form-group ">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>
                    <div class="form-group ">
                        {{ form.h_total.label_tag }}
                        {{ form.h_total }}
                    </div>
                    <div class="form-group ">
                        {{ form.h_remaining.label_tag }}
                        {{ form.h_remaining }}
                    </div>
                    <button type="submit" class="btn btn-dark">Valider</button>
                    <a class="btn btn-dark" href="{% url 'DSchool:student-list'%}">Retour</a>

                </form>
            </div>
        </div>
    </div>

</body>
</html>

drivingschool/DSchool/templates/DSchool/planning-all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votre Titre</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>


<div class="container-fluid">

    <div class="row justify-content-center mt-5">
        <div class="col-8">
    
            <h1>Planning</h1>
            <table class="table table-bordered table-striped table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Instructor</th>
                        <th scope="col">Adresse</th>
    
                    </tr>
                </thead>
                <tbody>
                    {% for planning in planning_liste %}
                    <tr>
                        <td><a href="{% url 'DSchool:student-detail' planning.student.id %}">{{ planning.student.username }}</a></td>
                        <td>{{ planning.date|date:"d-m-Y"  }}</td>
                        <td>{{ planning.date|date:"H:i" }}</td>
                        <td>{{ planning.instructor.username }}</td>
                        <td>{{ planning.place }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>



</body>
</html>

drivingschool/DSchool/templates/DSchool/planning.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planning-all</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>


<div class="container-fluid">

    <div class="row justify-content-center mt-5">
        <div class="col-8">

            <h1>Votre planning</h1>
            <h2>{{student.username}}</h2>
            <a href="{% url 'DSchool:add-rdv' student.id %}" class="btn btn-info">Ajouter un RDV</a>

            <table class="table table-bordered table-striped table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Heure</th>
                        <th scope="col">Instructor</th>
                        <th scope="col">Adresse</th>
    
                    </tr>
                </thead>
                <tbody>
                    {% for plan in plannings %}
                    <tr>
                        <td>{{ plan.date|date:"d-m-Y"  }}</td>
                        <td>{{ plan.date|date:"H:i" }}</td>
                        <td>{{ plan.instructor.username }}</td>
                        <td>{{ plan.place }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
      
        </div>
    </div>
</div>



</body>
</html>

drivingschool/DSchool/templates/DSchool/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votre Titre</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'DSchool/style.css' %}">
</head>
<body>



<div class="row justify-content-center mt-5">
    <div class="col-6">
        <h1>Driving School</h1>
        <h2>Students</h2>
        <a class="btn btn-dark" href="{% url 'DSchool:student_form' %}">Add a student</a>
        {% if student_list%}
            <table class="table table-bordered table-striped table-hover mt-4">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nom d'utilisateur</th>
                        <th scope="col">Planning</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in student_list%}
                    <tr>
                        
                        <td><a class="btn btn-link" href="{% url 'DSchool:student-detail' student.id %}">{{ student.username }}</a></td>
                        {% if student.planning_set.all %}
                        <td><a class="btn btn-dark" href="{% url 'DSchool:planning-list' student.id %}">Voir le planning</a></td>
                        {% else %}
                        <td> 
                        <a href="{% url 'DSchool:add-rdv' student.id %}" class="btn btn-info">Ajouter un RDV</a>
                        </td>
                        {% endif %}
                        <td class="d-flex">
                            <a class="btn btn-danger" href="{% url 'DSchool:student-to-delete' student.id %}">Supprimer</a>
                 
                            <a href="{% url 'DSchool:student-to-edit' student.id %}" class="btn btn-warning ml-2">Modifier</a>

                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
</div>


</body>
</html>

drivingschool/DSchool/templates/DSchool/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votre Titre</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid">

    <div class="row justify-content-center mt-5">
        <div class="col-8">

    
            <h1>Détails de l'étudiant : {{ student.username }}</h1>
            <a class="btn btn-dark" href="{% url 'DSchool:student-list'%}">Retour</a>
    
            <table class="table table-bordered table-striped table-hover mt-3">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nom d'utilisateur</th>
                        <th scope="col">Total d'heures</th>
                        <th scope="col">Heures restantes</th>
                        <th scope="col">Planning</th>
    
                        
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ student.username }}</td>
                        <td>{{ student.h_total }}</td>
                        <td>{{ student.h_remaining }}</td>
                        <td><a class="btn btn-dark" href="{% url 'DSchool:planning-list' student.id %}">Voir votre planning</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


</body>
</html>